version: '3.1'

volumes:
  data:

services:
  backend:
    build: .
    command: npm run dev
    restart: always
    ports:
      - '3030:3030'
    volumes:
      - ./src:/usr/src/app/src
      - ./config:/usr/src/app/config
      - /usr/src/app/node_modules
    depends_on:
      - mongo
    environment:
      - NODE_ENV=development

  frontend:
    build: ./client
    ports:
      - '8080:80'
    volumes:
      - ./client/public:/usr/src/app/public
      - ./client/src:/usr/src/app/src
      - /usr/client/app/node_modules
    links:
      - backend

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    restart: always
    volumes:
       - data:/data/db

