# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  backend:
    docker:
      - image: circleci/node-lts
    steps:
      - checkout
      - run: echo "A first hello"
  frontend:
    docker:
      - image: circleci/node-lts
    steps:
      - checkout
      - run: echo "A first hello"

workflows:
  version: 2
  backend_and_frontend:
    jobs:
      - backend
      - frontend
