# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  backend-testing:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
        name: Install Dependencies & Test
        command: npm install
  frontend-testing:
    docker:
      - image: circleci/node-lts
    steps:
      - checkout
      - run:
        name: Install Dependencies & Test
        command: echo here

workflows:
  version: 2
  tests_build:
    jobs:
      - backend-testing
      - frontend-testing
