# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  backend-testing:
    working_directory: ~/project
    docker:
      - image: circleci/node:lts
      - image: mongo:latest
    steps:
      - checkout
      - run: npm install
      - run: npm test
  frontend-testing:
    working_directory: ~/project/client
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run: npm install
      - run: npm test

workflows:
  version: 2
  tests_build:
    jobs:
      - backend-testing
      - frontend-testing

