# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  backend-testing:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - npm install
      - npm test
  frontend-testing:
    docker:
      - image: circleci/node-lts
    steps:
      - checkout
      - cd client
      - npm install
      - npm test

workflows:
  version: 2
  tests:
    jobs:
      - backend
      - frontend
